-- ============================================================
-- POS Minimarket - Creacion de tablas (Oracle)
-- Consolidado por: Integrante 1 (cada integrante aporta su tabla)
-- ============================================================

CREATE TABLE CATEGORIA (
    id_categoria  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR2(60)  NOT NULL,
    descripcion   VARCHAR2(150)
);

CREATE TABLE PRODUCTO (
    id_producto       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_barras     VARCHAR2(20) NOT NULL UNIQUE,
    nombre            VARCHAR2(100) NOT NULL,
    precio            NUMBER(8,2)   NOT NULL,
    stock             NUMBER        DEFAULT 0,
    tipo_producto     VARCHAR2(15)  NOT NULL,   -- PERECIBLE | POR_PESO | EMPAQUETADO
    fecha_vencimiento DATE,                      -- solo perecibles
    precio_por_kg     NUMBER(8,2),               -- solo por peso
    id_categoria      NUMBER,
    CONSTRAINT fk_producto_categoria FOREIGN KEY (id_categoria) REFERENCES CATEGORIA(id_categoria)
);

CREATE TABLE USUARIO (
    id_usuario  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR2(30) NOT NULL UNIQUE,
    password    VARCHAR2(64) NOT NULL,
    nombre      VARCHAR2(80) NOT NULL,
    rol         VARCHAR2(15) NOT NULL            -- ADMINISTRADOR | CAJERO
);

CREATE TABLE VENTA (
    id_venta     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha        TIMESTAMP DEFAULT SYSTIMESTAMP,
    total        NUMBER(10,2) NOT NULL,
    metodo_pago  VARCHAR2(15) NOT NULL,          -- EFECTIVO | TARJETA | YAPE | PLIN
    id_usuario   NUMBER NOT NULL,
    CONSTRAINT fk_venta_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario)
);

CREATE TABLE DETALLE_VENTA (
    id_detalle       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta         NUMBER NOT NULL,
    id_producto      NUMBER NOT NULL,
    cantidad         NUMBER NOT NULL,
    precio_unitario  NUMBER(8,2) NOT NULL,
    subtotal         NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_detalle_venta    FOREIGN KEY (id_venta)    REFERENCES VENTA(id_venta),
    CONSTRAINT fk_detalle_producto FOREIGN KEY (id_producto) REFERENCES PRODUCTO(id_producto)
);
